require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ExpenseManagement' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'ExpenseManagementTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
    # add the Firebase pod for Google Analytics
    pod 'Firebase'
    pod 'Firebase/InAppMessaging'
    pod 'Firebase/Analytics'
    pod 'Firebase/Messaging'
    # add pods for any other desired Firebase products
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ExpenseManagement-tvOS' do
  # Pods for ExpenseManagement-tvOS

  target 'ExpenseManagement-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
